### ISSUE TITLE
ClientInfo - Timezone related issue

### ISSUE THREAD

**Issue by zokodev** [zendesk/sunshine-conversations-java#9]
This looks like a timezone related issue. While invoking AppUserApi I'm getting the below error. I'm running the code from India (which is a +5.5 GMT timezone).  And the timezone field (in io.smooch.client.model.ClientInfo) is looking for an Integer. 

    java.lang.NumberFormatException: Expected an int but was 5.5 at line 1 column 306 path $.appUser.clients[0].info.timezone
	at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1204)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
	at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at com.google.gson.Gson.fromJson(Gson.java:927)
	at com.google.gson.Gson.fromJson(Gson.java:892)
	at com.google.gson.Gson.fromJson(Gson.java:841)
	at io.smooch.client.JSON.deserialize(JSON.java:103)
	at io.smooch.client.ApiClient.deserialize(ApiClient.java:842)
	at io.smooch.client.ApiClient.handleResponse(ApiClient.java:1045)
	at io.smooch.client.ApiClient.execute(ApiClient.java:972)
	at io.smooch.client.api.AppUserApi.getAppUserWithHttpInfo(AppUserApi.java:432)
	at io.smooch.client.api.AppUserApi.getAppUser(AppUserApi.java:417)

**Comment by mspensieri** [comment]
Thanks for the report, we'll look into it. Seems like an issue with the json parsing logic that assumes integer

**Comment by maxlacoste92** [comment]
Fixed in https://github.com/smooch/smooch-java/releases/tag/5.0
